name: Build palera1n for Linux x64

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-linux-x64.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-linux-x64.yml'
  workflow_dispatch:

jobs:
  build-Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build palera1n in Docker
        run: |
          docker build -t palera1n-builder -f- . <<EOF
          FROM ubuntu:20.04
          ENV DEBIAN_FRONTEND=noninteractive
          RUN apt-get update && apt-get install -y build-essential git libssl-dev libusb-1.0-0-dev libcurl4-openssl-dev libreadline-dev pkg-config autoconf automake libtool libimobiledevice-dev libusbmuxd-dev libplist-dev curl
          WORKDIR /palera1n
          COPY . .
          RUN make -j$(nproc)
          EOF
          docker create --name palera1n-container palera1n-builder
          docker cp palera1n-container:/palera1n/palera1n ./palera1n

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: palera1n-linux-x64
          path: palera1n