name: Build palera1n

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cygwin and required packages
        run: |
          choco install cygwin -y
          curl -LO https://cygwin.com/setup-x86_64.exe
          ./setup-x86_64.exe -q -P make,gcc-core,gcc-g++,libssl-devel,autoconf,automake,libtool

      - name: Add Cygwin to PATH
        run: |
          echo "C:\\tools\\cygwin\\bin" >> $GITHUB_PATH
          echo "C:\\tools\\cygwin\\usr\\local\\bin" >> $GITHUB_PATH
          echo "C:\\tools\\cygwin\\usr\\bin" >> $GITHUB_PATH

      - name: Install libusbmuxd
        shell: bash
        run: |
          curl -LO https://github.com/libimobiledevice/libusbmuxd/archive/refs/tags/2.0.2.tar.gz
          tar xzf 2.0.2.tar.gz
          cd libusbmuxd-2.0.2
          export PATH=/usr/local/bin:$PATH
          ./autogen.sh
          ./configure --prefix=/usr/local
          make
          make install

      - name: Build palera1n
        shell: bash
        run: |
          make all
