name: Build palera1n for Linux

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-linux.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-linux.yml'
  workflow_dispatch:

jobs:
  build-Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        triple:
          - x86_64-linux-musl
    env:
      MBEDTLS_VERSION: 3.5.2
      LIBUSB_VERSION: 1.0.27
      READLINE_VERSION: 8.2
      LIBIMOBILEDEVICE_COMMIT: ed0d66d0341562731bb19928dfe48155509fa7a7
      LIBIRECOVERY_COMMIT: 7ce02c347b7c26e59498e6af31c9da51018d0fa1
      LIBIMOBILEDEVICE_GLUE_COMMIT: 362f7848ac89b74d9dd113b38b51ecb601f76094
      LIBPLIST_COMMIT: 2117b8fdb6b4096455bd2041a63e59a028120136
      LIBUSBMUXD_COMMIT: a7f0543fb1ecb20ac7121c0fd77297200e0e43fc

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git autoconf automake libtool pkg-config

      - name: Setup environment
        run: |
          mkdir sysroot
          echo "DESTDIR=$(pwd)/sysroot" >> $GITHUB_ENV
          echo "PREFIX=/usr/local" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(pwd)/sysroot/usr/local/lib/pkgconfig" >> $GITHUB_ENV
          echo "CFLAGS=-I$(pwd)/sysroot/usr/local/include -L$(pwd)/sysroot/usr/local/lib" >> $GITHUB_ENV
          echo "LDFLAGS=-L$(pwd)/sysroot/usr/local/lib" >> $GITHUB_ENV
          echo "CONFIGURE_ARGS=--prefix=/usr/local --disable-shared --enable-static" >> $GITHUB_ENV

      - name: Build dependencies
        run: |
          set -e
          # Build MbedTLS
          curl -LO https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v${{ env.MBEDTLS_VERSION }}.tar.gz
          tar -xf v${{ env.MBEDTLS_VERSION }}.tar.gz
          cd mbedtls-${{ env.MBEDTLS_VERSION }}
          cmake -DCMAKE_INSTALL_PREFIX=${{ env.DESTDIR }}${{ env.PREFIX }} -DENABLE_PROGRAMS=OFF -DENABLE_TESTING=OFF .
          make -j$(nproc)
          make install
          cd ..

          # Build libusb
          curl -LO https://github.com/libusb/libusb/releases/download/v${{ env.LIBUSB_VERSION }}/libusb-${{ env.LIBUSB_VERSION }}.tar.bz2
          tar -xjf libusb-${{ env.LIBUSB_VERSION }}.tar.bz2
          cd libusb-${{ env.LIBUSB_VERSION }}
          ./configure ${{ env.CONFIGURE_ARGS }}
          make -j$(nproc)
          make install DESTDIR=${{ env.DESTDIR }}
          cd ..

          # Build readline
          curl -LO https://ftp.gnu.org/gnu/readline/readline-${{ env.READLINE_VERSION }}.tar.gz
          tar -xzf readline-${{ env.READLINE_VERSION }}.tar.gz
          cd readline-${{ env.READLINE_VERSION }}
          ./configure ${{ env.CONFIGURE_ARGS }}
          make -j$(nproc)
          make install DESTDIR=${{ env.DESTDIR }}
          cd ..

          # Build other dependencies (libplist, libimobiledevice-glue, libirecovery, libusbmuxd, libimobiledevice)
          for repo in libplist libimobiledevice-glue libirecovery libusbmuxd libimobiledevice; do
            git clone https://github.com/libimobiledevice/$repo.git
            cd $repo
            ./autogen.sh
            ./configure ${{ env.CONFIGURE_ARGS }}
            make -j$(nproc)
            make install DESTDIR=${{ env.DESTDIR }}
            cd ..
          done

      - name: Build palera1n
        run: |
          make -j$(nproc) ROOTFUL=1 V=1

      - name: Verify binary
        run: |
          file src/palera1n
          ldd src/palera1n || true
          ./src/palera1n --version

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: palera1n-linux-x86_64
          path: src/palera1n