name: Build palera1n for Windows

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-windows.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-windows.yml'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          packages: make gcc-core gcc-g++ pkg-config libssl-devel libusb1.0-devel libreadline-devel

      - name: Build palera1n
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          cd "$GITHUB_WORKSPACE"
          make -j$(nproc) ROOTFUL=1

      - name: Prepare artifact
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          mkdir -p ready/binaries
          cp src/palera1n.exe ready/binaries/palera1n-windows.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: palera1n-windows
          path: ready/binaries/palera1n-windows.exe
