name: Build palera1n for Linux x64

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-linux-x64.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-linux-x64.yml'
  workflow_dispatch:

jobs:
  build-Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build palera1n in Docker
        run: |
          docker build -t palera1n-builder -f- . <<EOF
          FROM ubuntu:20.04
          ENV DEBIAN_FRONTEND=noninteractive
          RUN apt-get update && apt-get install -y build-essential git libssl-dev libusb-1.0-0-dev libcurl4-openssl-dev libreadline-dev pkg-config autoconf automake libtool python3-dev curl

          # Function to build and install a library with error logging
          RUN echo 'build_and_install() { \
              echo "Building $1..." && \
              git clone https://github.com/libimobiledevice/$1.git && \
              cd $1 && \
              ./autogen.sh && \
              ./configure && \
              make && \
              make install && \
              ldconfig && \
              cd .. || { echo "Error building $1"; cat config.log; exit 1; } \
          }' >> /root/.bashrc

          # Build and install dependencies
          RUN . /root/.bashrc && \
              build_and_install libplist && \
              build_and_install libusbmuxd && \
              build_and_install libimobiledevice-glue && \
              build_and_install libimobiledevice && \
              build_and_install libirecovery

          WORKDIR /palera1n
          COPY . .
          RUN PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH make -j$(nproc) || { echo "Build failed. Makefile contents:"; cat Makefile; exit 1; }
          EOF
          docker create --name palera1n-container palera1n-builder
          docker cp palera1n-container:/palera1n/palera1n ./palera1n || { echo "Failed to copy palera1n binary. Container logs:"; docker logs palera1n-container; exit 1; }

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: palera1n-linux-x64
          path: palera1n