name: Build palera1n

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Chocolatey
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install Cygwin
        shell: powershell
        run: choco install cygwin -y

      - name: Add Cygwin to PATH
        shell: powershell
        run: echo "C:\\tools\\cygwin\\bin" >> $env:GITHUB_PATH

      - name: Install required packages with Cygwin
        shell: bash
        run: |
          /cygwin64/bin/bash -c "apt-cyg install make gcc-core gcc-g++ libssl-devel"

      - name: Build palera1n
        shell: bash
        run: |
          /cygwin64/bin/bash -c "make all"
