name: Build palera1n for Windows

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cross-compilation tools
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Install dependencies
        run: sudo apt-get install -y autoconf automake libtool pkg-config

      - name: Build and install libusbmuxd
        run: |
          curl -LO https://github.com/libimobiledevice/libusbmuxd/archive/refs/tags/2.0.2.tar.gz
          tar xzf 2.0.2.tar.gz
          cd libusbmuxd-2.0.2
          ./autogen.sh
          ./configure --host=x86_64-w64-mingw32 --prefix=/usr/local/x86_64-w64-mingw32
          make
          sudo make install

      - name: Build palera1n
        run: |
          export PATH=/usr/local/x86_64-w64-mingw32/bin:$PATH
          make CC=x86_64-w64-mingw32-gcc
