name: Build palera1n

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cygwin and required packages
        run: |
          choco install cygwin -y
          choco install cyg-get -y
          cyg-get install make gcc-core gcc-g++ libssl-devel autoconf automake libtool

      - name: Add Cygwin to PATH
        run: echo "C:\\tools\\cygwin\\bin" >> $GITHUB_PATH

      - name: Setup environment
        run: |
          export PKG_CONFIG_PATH=/usr/local/x86_64-w64-mingw32/lib/pkgconfig
          export PATH=/usr/local/x86_64-w64-mingw32/bin:$PATH

      - name: Build and install libplist
        run: |
          curl -LO https://github.com/libimobiledevice/libplist/archive/refs/tags/2.2.0.tar.gz
          tar xzf 2.2.0.tar.gz
          cd libplist-2.2.0
          ./autogen.sh
          ./configure --host=x86_64-w64-mingw32 --prefix=/usr/local/x86_64-w64-mingw32 --disable-shared --enable-static
          make
          make install

      - name: Patch and build libusbmuxd
        run: |
          curl -LO https://github.com/libimobiledevice/libusbmuxd/archive/refs/tags/2.0.2.tar.gz
          tar xzf 2.0.2.tar.gz
          cd libusbmuxd-2.0.2
          sed -i 's/AI_NUMERICSERV/0/g' src/socket.c
          sed -i 's/freeifaddrs/if_freenameindex/g' src/socket.c
          sed -i '/#include <sys\/socket.h>/a #include <ws2tcpip.h>' src/socket.c
          sed -i '/#include <sys\/socket.h>/a #include <winsock2.h>' src/socket.c
          ./autogen.sh
          ./configure --host=x86_64-w64-mingw32 --prefix=/usr/local/x86_64-w64-mingw32 --disable-shared --enable-static
          make
          make install

      - name: Build palera1n
        run: |
          make CC=x86_64-w64-mingw32-gcc
        env:
          PKG_CONFIG_PATH: /usr/local/x86_64-w64-mingw32/lib/pkgconfig
          libplist_CFLAGS: $(pkg-config --cflags libplist-2.0)
          libplist_LIBS: $(pkg-config --libs libplist-2.0)