name: Build palera1n

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Cygwin
        run: |
          choco install cygwin --params "/InstallDir:C:\\cygwin64"
          echo "::add-path::C:\\cygwin64\\bin"

      - name: Install Cygwin packages
        run: |
          C:\\cygwin64\\setup-x86_64.exe -q -P make,gcc-core,gcc-g++,libssl-devel

      - name: Build palera1n
        run: |
          C:\\cygwin64\\bin\\bash -c "make -j$(nproc)"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: palera1n-windows
          path: ./src/palera1n
