name: Build palera1n for Linux x64

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-linux-x64.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-linux-x64.yml'
  workflow_dispatch:

jobs:
  build-Linux:
    runs-on: ubuntu-latest
    env:
      MBEDTLS_VERSION: 3.5.2
      LIBUSB_VERSION: 1.0.27
      LIBIMOBILEDEVICE_COMMIT: ed0d66d0341562731bb19928dfe48155509fa7a7
      LIBIRECOVERY_COMMIT: 7ce02c347b7c26e59498e6af31c9da51018d0fa1
      LIBIMOBILEDEVICE_GLUE_COMMIT: 362f7848ac89b74d9dd113b38b51ecb601f76094
      LIBPLIST_COMMIT: 2117b8fdb6b4096455bd2041a63e59a028120136
      LIBUSBMUXD_COMMIT: a7f0543fb1ecb20ac7121c0fd77297200e0e43fc

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git autoconf automake libtool pkg-config libssl-dev libusb-1.0-0-dev libcurl4-openssl-dev

      - name: Setup environment
        run: |
          mkdir -p sysroot/usr/local/{lib,include}
          echo "DESTDIR=$(pwd)/sysroot" >> $GITHUB_ENV
          echo "PREFIX=/usr/local" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(pwd)/sysroot/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "CFLAGS=-I$(pwd)/sysroot/usr/local/include -I$(pwd)/sysroot/usr/local/include/libusb-1.0 -L$(pwd)/sysroot/usr/local/lib" >> $GITHUB_ENV
          echo "LDFLAGS=-L$(pwd)/sysroot/usr/local/lib" >> $GITHUB_ENV
          echo "CONFIGURE_ARGS=--prefix=/usr/local --disable-shared --enable-static" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$(pwd)/sysroot/usr/local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Build dependencies
        run: |
          set -ex
          # Build MbedTLS
          curl -LO https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v${{ env.MBEDTLS_VERSION }}.tar.gz
          tar -xf v${{ env.MBEDTLS_VERSION }}.tar.gz
          cd mbedtls-${{ env.MBEDTLS_VERSION }}
          cmake -DCMAKE_INSTALL_PREFIX=${{ env.DESTDIR }}${{ env.PREFIX }} -DENABLE_PROGRAMS=OFF -DENABLE_TESTING=OFF -DCMAKE_BUILD_TYPE=Release .
          make -j$(nproc)
          make install
          cd ..

          # Build libusb
          curl -LO https://github.com/libusb/libusb/releases/download/v${{ env.LIBUSB_VERSION }}/libusb-${{ env.LIBUSB_VERSION }}.tar.bz2
          tar -xjf libusb-${{ env.LIBUSB_VERSION }}.tar.bz2
          cd libusb-${{ env.LIBUSB_VERSION }}
          ./configure ${{ env.CONFIGURE_ARGS }} --disable-udev
          make -j$(nproc)
          make install DESTDIR=${{ env.DESTDIR }}
          cd ..

          # Build other dependencies (libplist, libimobiledevice-glue, libirecovery, libusbmuxd, libimobiledevice)
          for repo in libplist libimobiledevice-glue libirecovery libusbmuxd libimobiledevice; do
            git clone https://github.com/libimobiledevice/$repo.git
            cd $repo
            ./autogen.sh
            ./configure ${{ env.CONFIGURE_ARGS }} \
              CFLAGS="${{ env.CFLAGS }}" \
              LDFLAGS="${{ env.LDFLAGS }}" \
              PKG_CONFIG_PATH="${{ env.PKG_CONFIG_PATH }}"
            make -j$(nproc)
            make install DESTDIR=${{ env.DESTDIR }}
            cd ..
          done

          # Fix .la files
          find ${{ env.DESTDIR }}${{ env.PREFIX }}/lib -name '*.la' -exec sed -i \
            -e 's|^libdir=.*|libdir='"'${{ env.DESTDIR }}${{ env.PREFIX }}/lib'"'|' \
            -e 's|^dependency_libs=.*|dependency_libs=|' \
            -e 's| /usr/local/lib/lib| ${{ env.DESTDIR }}/usr/local/lib/lib|g' {} +

      - name: Build palera1n
        run: |
          export PKG_CONFIG_PATH=${{ env.PKG_CONFIG_PATH }}
          export CFLAGS="${{ env.CFLAGS }}"
          export LDFLAGS="${{ env.LDFLAGS }}"
          export LD_LIBRARY_PATH="${{ env.LD_LIBRARY_PATH }}"
          make -j$(nproc) ROOTFUL=1

      - name: Verify binary
        run: |
          file src/palera1n
          ldd src/palera1n || true
          LD_LIBRARY_PATH=${{ env.LD_LIBRARY_PATH }} ./src/palera1n --version || true

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: palera1n-linux-x64
          path: src/palera1n