name: Build palera1n for Windows

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-windows.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-windows.yml'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      CYGWIN_ROOT: C:\cygwin64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: make gcc-core gcc-g++ pkg-config autoconf automake libtool git

      - name: Setup environment
        run: |
          echo "${{ env.CYGWIN_ROOT }}/bin" >> $GITHUB_PATH
          echo "CFLAGS=-g -O2" >> $GITHUB_ENV
          echo "CXXFLAGS=-g -O2" >> $GITHUB_ENV
          echo "LDFLAGS=-g" >> $GITHUB_ENV

      - name: Build palera1n
        shell: bash
        run: |
          export PATH="/usr/bin:$PATH"
          make -j$(nproc) ROOTFUL=1

      - name: Prepare artifact
        run: |
          mkdir -p artifacts
          cp src/palera1n.exe artifacts/palera1n-windows.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: palera1n-windows
          path: artifacts/palera1n-windows.exe