name: Build palera1n for Linux x64

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-linux-x64.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-linux-x64.yml'
  workflow_dispatch:

jobs:
  build-Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libimobiledevice-dev libusbmuxd-dev libplist-dev libssl-dev libusb-1.0-0-dev libtool-bin build-essential git autoconf automake libtool pkg-config checkinstall libcurl4-openssl-dev

      - name: Build and install libplist
        run: |
          git clone https://github.com/libimobiledevice/libplist.git
          cd libplist
          ./autogen.sh
          ./configure
          make
          sudo make install
          sudo ldconfig
          cd ..

      - name: Build and install libimobiledevice-glue
        run: |
          git clone https://github.com/libimobiledevice/libimobiledevice-glue.git
          cd libimobiledevice-glue
          ./autogen.sh
          ./configure
          make
          sudo make install
          sudo ldconfig
          cd ..

      - name: Build and install libusbmuxd
        run: |
          git clone https://github.com/libimobiledevice/libusbmuxd.git
          cd libusbmuxd
          ./autogen.sh
          ./configure
          make
          sudo make install
          sudo ldconfig
          cd ..

      - name: Build and install libtatsu
        run: |
          git clone https://github.com/libimobiledevice/libtatsu.git
          cd libtatsu
          ./autogen.sh
          ./configure
          make
          sudo make install
          sudo ldconfig
          cd ..

      - name: Build and install libimobiledevice
        run: |
          git clone https://github.com/libimobiledevice/libimobiledevice.git
          cd libimobiledevice
          ./autogen.sh
          ./configure
          make
          sudo make install
          sudo ldconfig
          cd ..

      - name: Build and install libirecovery
        run: |
          git clone https://github.com/libimobiledevice/libirecovery.git
          cd libirecovery
          ./autogen.sh
          ./configure
          make
          sudo make install
          sudo ldconfig
          cd ..

      - name: Build palera1n
        run: |
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
          export CFLAGS="-I/usr/local/include $CFLAGS"
          export LDFLAGS="-L/usr/local/lib $LDFLAGS"
          make -j$(nproc) CFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: palera1n-linux-x64
          path: palera1n
