name: Build palera1n for Linux x64

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-linux-x64.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/build-linux-x64.yml'
  workflow_dispatch:

jobs:
  build-Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libimobiledevice-dev libusbmuxd-dev libplist-dev libssl-dev libusb-1.0-0-dev

      - name: Build palera1n
        run: make -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: palera1n-linux-x64
          path: palera1n