name: Build palera1n for Linux x86

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'docs/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libusb-1.0-0-dev libssl-dev

      - name: Install dependencies
        run: |
          sudo apt-get install -y autoconf automake libtool

      - name: Download and Build Dependencies
        run: |
          # Placeholder for commands to download and build any external libraries
          echo "Downloading and building external dependencies"

      - name: Build palera1n
        run: |
          make

      - name: Prepare artifact
        run: |
          mkdir -p output
          cp src/palera1n output/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: palera1n-linux-x86
          path: output/

