name: Build palera1n

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Cygwin
        run: |
          choco install cygwin
          choco install cygwin --params "'/InstallDir:C:\\cygwin64 /Packages:make,gcc-core,gcc-g++,libssl-devel'"

      - name: Add Cygwin to PATH
        run: echo "C:\\cygwin64\\bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          C:\\cygwin64\\bin\\bash -c "apt-cyg install make gcc-core gcc-g++ libssl-devel"

      - name: Build palera1n
        run: |
          C:\\cygwin64\\bin\\bash -c "make -j$(nproc)"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: palera1n-windows
          path: ./src/palera1n

