name: Cygwin Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-cygwin:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cygwin
        run: |
          curl -L -O https://cygwin.com/setup-x86_64.exe
          .\setup-x86_64.exe -q -P cygport,git,make,gcc-core

      - name: Debug Cygwin installation
        shell: pwsh
        run: |
          Get-ChildItem "C:\cygwin64\bin"
          & "C:\cygwin64\bin\bash.exe" --version

      - name: Verify cygport and git installation
        shell: pwsh
        run: |
          & "C:\cygwin64\bin\bash.exe" -lc "cygport --version"
          & "C:\cygwin64\bin\bash.exe" -lc "git --version"

      - name: Check Cygwin PATH
        shell: pwsh
        run: |
          $env:Path += ";C:\cygwin64\bin"
          $env:Path -split ';'
          Get-Command bash.exe | Format-List *
          Get-Command cygport | Format-List *
          Get-Command git | Format-List *