name: Cygwin Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-cygwin:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cygwin
        shell: cmd
        run: |
          curl -L -o setup-x86_64.exe https://cygwin.com/setup-x86_64.exe
          setup-x86_64.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --only-site --root C:\cygwin64 --site http://cygwin.mirror.constant.com --packages cygport,git,make,gcc-core

      - name: Debug Cygwin installation
        shell: cmd
        run: |
          dir C:\cygwin64
          dir C:\cygwin64\bin
          C:\cygwin64\bin\bash.exe --version

      - name: Verify cygport and git installation
        shell: cmd
        run: |
          C:\cygwin64\bin\bash.exe -lc "cygport --version"
          C:\cygwin64\bin\bash.exe -lc "git --version"

      - name: Check system PATH
        shell: cmd
        run: |
          echo %PATH%