name: Build palera1n Windows x64

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Cygwin and required packages
        run: |
          # Download Cygwin installer
          Invoke-WebRequest -Uri https://cygwin.com/setup-x86_64.exe -OutFile setup-x86_64.exe
          
          # Install Cygwin with required packages
          Start-Process -FilePath .\setup-x86_64.exe -ArgumentList '-q -P cygport,git,make,gcc-core,libncurses-devel,autoconf,automake,binutils,coreutils,gnupg,gzip,terminfo,terminfo-extra' -NoNewWindow -Wait

      - name: Add Cygwin to PATH
        run: |
          $env:Path = "C:\cygwin64\bin;C:\cygwin64\usr\local\bin;C:\cygwin64\usr\bin;" + $env:Path

      - name: Verify cygport
        run: |
          if (Test-Path "C:\cygwin64\bin\cygport.exe") {
            Write-Output "cygport is installed and available."
            & "C:\cygwin64\bin\cygport.exe" --version
          } else {
            Write-Output "cygport is not installed."
            exit 1
          }
