name: Windows Build with WSL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Enable WSL
        run: |
          wsl --install -d Ubuntu
        shell: powershell

      - name: Setup WSL
        run: |
          wsl sudo apt-get update
          wsl sudo apt-get install -y build-essential git autoconf automake libtool pkg-config
        shell: powershell

      - name: Build libplist in WSL
        run: |
          wsl bash -c '
            git clone https://github.com/libimobiledevice/libplist.git
            cd libplist
            ./autogen.sh
            ./configure
            make
            sudo make install
            cd ..
          '
        shell: powershell

      - name: Build palera1n in WSL
        run: |
          wsl bash -c '
            cd ${{ github.workspace }}
            # Add your palera1n build commands here, for example:
            # make
          '
        shell: powershell

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: palera1n-windows
          path: ${{ github.workspace }}/palera1n.exe  # Adjust this path as needed