name: Build palera1n Windows x64

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and Install Cygwin
        run: |
          curl -L -O https://cygwin.com/setup-x86_64.exe
          ./setup-x86_64.exe -q -D -R C:\cygwin64 -s http://cygwin.mirror.constant.com/
          ./setup-x86_64.exe -q -L -R C:\cygwin64 -P cygport,git,make,gcc-core,libncurses-devel,autoconf,automake,binutils,coreutils,gnupg,gzip,terminfo,terminfo-extra

      - name: Check Cygwin installation directories
        run: |
          echo "Checking Cygwin root directory contents"
          dir C:\cygwin64
          echo "Checking Cygwin bin directory contents"
          dir C:\cygwin64\bin

      - name: Verify Cygwin bin directory exists
        run: |
          if [ -d "C:\cygwin64\bin" ]; then
            echo "Cygwin bin directory exists"
          else
            echo "Cygwin bin directory does NOT exist"
            exit 1
          fi
        shell: bash

      - name: Create symlink for Cygwin bin if needed
        run: |
          if [ ! -d "/cygdrive/c/cygwin64/bin" ]; then
            echo "Creating symlink for Cygwin bin directory"
            mkdir -p /cygdrive/c/cygwin64
            mkdir -p /cygdrive/c/cygwin64_usr_bin
            ln -s /cygdrive/c/cygwin64/bin /cygdrive/c/cygwin64_usr_bin/bin
          fi
        shell: bash

      - name: Setup Cygwin