name: Build palera1n Windows x64 (Cygwin)

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cygwin and required packages
        run: |
          Invoke-WebRequest -Uri https://cygwin.com/setup-x86_64.exe -OutFile setup-x86_64.exe
          .\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P git,make,gcc-core,gcc-g++,libncurses-devel,autoconf,automake,libtool,pkg-config,libssl-devel,libusb1.0-devel,libcurl-devel,libreadline-devel,zlib-devel,cmake,python3,python3-pip

      - name: Set up Cygwin environment
        run: |
          echo "C:\cygwin64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "CYGWIN=winsymlinks:native" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build dependencies
        shell: C:\cygwin64\bin\bash.exe --login -o igncr '{0}'
        run: |
          cd $GITHUB_WORKSPACE
          # Build and install libplist
          git clone https://github.com/libimobiledevice/libplist.git
          cd libplist
          ./autogen.sh
          ./configure --prefix=/usr/local
          make
          make install
          cd ..

          # Build and install libimobiledevice-glue
          git clone https://github.com/libimobiledevice/libimobiledevice-glue.git
          cd libimobiledevice-glue
          ./autogen.sh
          ./configure --prefix=/usr/local
          make
          make install
          cd ..

          # Build and install libusbmuxd
          git clone https://github.com/libimobiledevice/libusbmuxd.git
          cd libusbmuxd
          ./autogen.sh
          ./configure --prefix=/usr/local
          make
          make install
          cd ..

          # Build and install libimobiledevice
          git clone https://github.com/libimobiledevice/libimobiledevice.git
          cd libimobiledevice
          ./autogen.sh
          ./configure --prefix=/usr/local
          make
          make install
          cd ..

      - name: Build palera1n
        shell: C:\cygwin64\bin\bash.exe --login -o igncr '{0}'
        run: |
          cd $GITHUB_WORKSPACE
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
          make

      - name: Package palera1n
        shell: C:\cygwin64\bin\bash.exe --login -o igncr '{0}'
        run: |
          mkdir -p artifact
          cp palera1n artifact/palera1n.exe
          cp /usr/local/bin/cygwin1.dll artifact/
          # Add any other necessary DLLs here

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: palera1n-windows-x64
          path: artifact