name: Build palera1n Windows x64

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build-windows-x64:
    runs-on: windows-latest
    env:
      MSYS2_VERSION: 20210604
      MSYS2_PATH: C:\msys64
      MINGW_PREFIX: mingw-w64-x86_64
      MBEDTLS_VERSION: 3.5.2
      LIBUSB_VERSION: 1.0.27
      READLINE_VERSION: 8.2
      GPM_VERSION: 1.20.7
      LIBIMOBILEDEVICE_COMMIT: ed0d66d0341562731bb19928dfe48155509fa7a7
      LIBIRECOVERY_COMMIT: 7ce02c347b7c26e59498e6af31c9da51018d0fa1
      LIBIMOBILEDEVICE_GLUE_COMMIT: 362f7848ac89b74d9dd113b38b51ecb601f76094
      USBMUXD_COMMIT: bc0b91ca856811f4393318dc83db6dc3c1ac326d
      LIBPLIST_COMMIT: 2117b8fdb6b4096455bd2041a63e59a028120136
      LIBUSBMUXD_COMMIT: a7f0543fb1ecb20ac7121c0fd77297200e0e43fc

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Cygwin and cygport
        run: |
          curl -L -O https://cygwin.com/setup-x86_64.exe
          ./setup-x86_64.exe -q -P cygport,git,make,gcc-core,libncurses-devel,autoconf,automake,binutils,coreutils,gnupg,gzip,terminfo,terminfo-extra

      - name: Setup Cygwin Environment
        run: |
          echo "C:\\cygwin64\\bin" >> $GITHUB_PATH
          echo "C:\\cygwin64\\usr\\local\\bin" >> $GITHUB_PATH
          echo "C:\\cygwin64\\usr\\bin" >> $GITHUB_PATH

      - name: Verify cygport and git installation
        run: |
          C:\\cygwin64\\bin\\bash -lc "cygport --version"
          C:\\cygwin64\\bin\\bash -lc "git --version"

      - name: Build readline
        run: |
          C:\\cygwin64\\bin\\bash -lc "
          export PATH=/usr/bin:/mingw64/bin:$PATH
          git clone git://cygwin.com/git/cygwin-packages/readline.git
          cd readline
          cygport readline.cygport download all
          cd \$(cygport readline.cygport dir)
          ./configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --prefix=/mingw64 --disable-shared --enable-static
          make -j\$(nproc)
          make install
          "

      - name: Build other dependencies
        run: |
          C:\\cygwin64\\bin\\bash -lc "
          git clone https://github.com/libimobiledevice/libplist.git
          cd libplist
          git fetch origin ${{ env.LIBPLIST_COMMIT }} && git reset --hard ${{ env.LIBPLIST_COMMIT }}
          ./autogen.sh
          ./configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --prefix=/mingw64
          make -j\$(nproc)
          make install
          "
