name: Build palera1n Windows x64

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and Install Cygwin
        run: |
          curl -L -O https://cygwin.com/setup-x86_64.exe
          ./setup-x86_64.exe -q -D -R C:\cygwin64 -s http://cygwin.mirror.constant.com/
          ./setup-x86_64.exe -q -L -R C:\cygwin64 -P cygport,git,make,gcc-core,libncurses-devel,autoconf,automake,binutils,coreutils,gnupg,gzip,terminfo,terminfo-extra

      - name: Setup Cygwin Environment and Verify
        shell: bash
        run: |
          export PATH=/cygdrive/c/cygwin64/bin:/cygdrive/c/cygwin64/usr/local/bin:/cygdrive/c/cygwin64/usr/bin:$PATH
          echo "PATH set to: $PATH"
          ls -la /cygdrive/c/cygwin64/bin
          which cygport
          cygport --version
