name: Windows Build with MinGW-w64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up MinGW-w64
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Install dependencies
        run: |
          choco install -y wget make
        shell: pwsh

      - name: Prepare build environment
        run: |
          $mingwPath = "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64"
          $env:PATH = "$mingwPath\bin;$env:PATH"
          echo "MINGW_PATH=$mingwPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Build libplist
        run: |
          git clone https://github.com/libimobiledevice/libplist.git
          cd libplist
          ./autogen.sh
          ./configure --host=x86_64-w64-mingw32 --prefix=${{ env.MINGW_PATH }}
          make
          make install
          cd ..
        shell: msys2 {0}

      - name: Build palera1n
        run: |
          # Add your palera1n build commands here, for example:
          # make LDFLAGS="-L${{ env.MINGW_PATH }}/lib" CFLAGS="-I${{ env.MINGW_PATH }}/include"
        shell: msys2 {0}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: palera1n-windows
          path: palera1n.exe  # Adjust this path as needed