name: Cygwin Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-cygwin:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cygwin
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest https://cygwin.com/setup-x86_64.exe -OutFile setup-x86_64.exe
          Start-Process -FilePath .\setup-x86_64.exe -ArgumentList "-q -P cygport,git,make,gcc-core" -NoNewWindow -Wait
          Get-ChildItem C:\ -Directory -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.Name -eq "cygwin64" }

      - name: Debug Cygwin installation
        shell: pwsh
        run: |
          $cygwinPath = Get-ChildItem C:\ -Directory -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.Name -eq "cygwin64" } | Select-Object -First 1 -ExpandProperty FullName
          if ($cygwinPath) {
            Write-Host "Cygwin installed at: $cygwinPath"
            Get-ChildItem "$cygwinPath\bin"
            & "$cygwinPath\bin\bash.exe" --version
          } else {
            Write-Host "Cygwin installation not found"
          }

      - name: Verify cygport and git installation
        shell: pwsh
        run: |
          $cygwinPath = Get-ChildItem C:\ -Directory -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.Name -eq "cygwin64" } | Select-Object -First 1 -ExpandProperty FullName
          if ($cygwinPath) {
            & "$cygwinPath\bin\bash.exe" -lc "cygport --version"
            & "$cygwinPath\bin\bash.exe" -lc "git --version"
          } else {
            Write-Host "Cygwin installation not found"
          }

      - name: Check system PATH
        shell: pwsh
        run: |
          $env:Path -split ';'