name: Windows Build with MinGW-w64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up MinGW-w64
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Install dependencies
        run: |
          choco install -y wget
          choco install -y make
        shell: pwsh

      - name: Build libplist
        run: |
          git clone https://github.com/libimobiledevice/libplist.git
          cd libplist
          ./autogen.sh
          ./configure --host=x86_64-w64-mingw32 --prefix=/c/libplist
          make
          make install
          cd ..
        shell: msys2 {0}

      - name: Build palera1n
        run: |
          # Add your palera1n build commands here, for example:
          # make LDFLAGS="-L/c/libplist/lib" CFLAGS="-I/c/libplist/include"
        shell: msys2 {0}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: palera1n-windows
          path: palera1n.exe  # Adjust this path as needed